---
####################
### RabbitMQ
####################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.10.1-alpine
          # https://hub.docker.com/_/rabbitmq
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  #type: LoadBalancer
  ports:
    - targetPort: amqp
      port: 5672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    appd-instr: enabled
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: appdynamics/demo/java/order-service
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dspring.profiles.active=k8s"
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - targetPort: http
      port: 8080
